// Code generated by k8s code-generator DO NOT EDIT.

/*
Copyright 2018 Google LLC

Licensed under the Apache License, Version 2.0 (the "License");
you may not use this file except in compliance with the License.
You may obtain a copy of the License at

    https://www.apache.org/licenses/LICENSE-2.0

Unless required by applicable law or agreed to in writing, software
distributed under the License is distributed on an "AS IS" BASIS,
WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
See the License for the specific language governing permissions and
limitations under the License.
*/
// Code generated by client-gen. DO NOT EDIT.

package fake

import (
	v1 "github.com/bstadlbauer/dask-k8s-operator-go-client/pkg/client/clientset/versioned/typed/kubernetes.dask.org/v1"
	rest "k8s.io/client-go/rest"
	testing "k8s.io/client-go/testing"
)

type FakeKubernetesV1 struct {
	*testing.Fake
}

func (c *FakeKubernetesV1) DaskClusters(namespace string) v1.DaskClusterInterface {
	return &FakeDaskClusters{c, namespace}
}

func (c *FakeKubernetesV1) DaskJobs(namespace string) v1.DaskJobInterface {
	return &FakeDaskJobs{c, namespace}
}

func (c *FakeKubernetesV1) DaskWorkerGroups(namespace string) v1.DaskWorkerGroupInterface {
	return &FakeDaskWorkerGroups{c, namespace}
}

// RESTClient returns a RESTClient that is used to communicate
// with API server by this client implementation.
func (c *FakeKubernetesV1) RESTClient() rest.Interface {
	var ret *rest.RESTClient
	return ret
}
