name: pre-commit

on:
  pull_request:
  push:
    branches: [main]

jobs:
  pre-commit:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    - uses: actions/setup-python@v3
    - name: Setup Go
      uses: actions/setup-go@v2
      with:
        go-version: ‘1.18.0’
    - name: Install go dependencies
      run: |
        go install github.com/fzipp/gocyclo/cmd/gocyclo@v0.6.0
        go install github.com/go-critic/go-critic/cmd/gocritic@v0.6.5
        go install github.com/golangci/golangci-lint/cmd/golangci-lint@v1.50.1
        go install golang.org/x/tools/cmd/goimports@v0.2.0
    - uses: pre-commit/action@v3.0.0
